name: active_record_proxy_adapters

x-app-common: &app-common
  image: active_record_proxy_adapters-app:${ENV_TAG:-latest}

x-healthcheck_common: &healthcheck-common
  interval: 5s
  timeout: 10s
  retries: 30

x-postgres-common: &postgres-common
  restart: always
  user: postgres
  healthcheck:
    <<: *healthcheck-common
    test: 'pg_isready -U postgres_primary_test --dbname=postgres'
  networks:
    - postgres

services:
  app:
    <<: *app-common
    build:
      args:
        - RUBY_VERSION=${RUBY_VERSION:-3.4.6}
        - DOCKER_REGISTRY=${DOCKER_REGISTRY:-docker.io}
    container_name: app
    tty: true
    stdin_open: true
    environment:
      - RAILS_VERSION=${RAILS_VERSION:-8.0.0}
      - PGHOST=postgres_primary
      - PG_PRIMARY_USER=postgres_primary_test
      - PG_PRIMARY_PASSWORD=postgres_primary_test
      - PG_PRIMARY_HOST=postgres_primary
      - PG_PRIMARY_PORT=5432
      - PG_REPLICA_USER=postgres_primary_test
      - PG_REPLICA_PASSWORD=postgres_primary_test
      - PG_REPLICA_HOST=postgres_replica
      - PG_REPLICA_PORT=5432
      - MYSQL_PRIMARY_USER=root
      - MYSQL_PRIMARY_PASSWORD=mysql
      - MYSQL_PRIMARY_HOST=mysql_primary
      - MYSQL_PRIMARY_PORT=3306
      - MYSQL_REPLICA_USER=root
      - MYSQL_REPLICA_PASSWORD=mysql
      - MYSQL_REPLICA_HOST=mysql_primary
      - MYSQL_REPLICA_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_URL=${REDIS_URL:-redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DATABASE:-0}}
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
      - MEMCACHED_URL=${MEMCACHED_URL:-${MEMCACHED_HOST:-memcached}:${MEMCACHED_PORT:-11211}}
    depends_on:
      postgres_primary:
        condition: service_healthy
      postgres_replica:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    networks:
      - app
      - postgres
      - mariadb
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 8808:8808
  postgres_primary:
    <<: *postgres-common
    build:
      context: docker/postgres_primary
      args:
        - POSTGRES_LOGGING_COLLECTOR=${POSTGRES_LOGGING_COLLECTOR:-}
        - POSTGRES_LOG_DESTINATION=${POSTGRES_LOG_DESTINATION:-}
        - POSTGRES_LOG_STATEMENT=${POSTGRES_LOG_STATEMENT:-}
        - REPLICA_USER=replicator
        - REPLICA_PASSWORD=replicator
    container_name: postgres_primary
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_primary_test
      POSTGRES_PASSWORD: postgres_primary_test
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_primary:/var/lib/postgresql/data

  postgres_replica:
    <<: *postgres-common
    build:
      context: docker/postgres_replica
    container_name: postgres_replica
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator
      PRIMARY_DATABASE_HOST: postgres_primary
    volumes:
      - postgres_replica:/var/lib/postgresql/data
    depends_on:
      postgres_primary:
        condition: service_healthy
  # TODO: create mysql replica images
  mariadb:
    image: mariadb:11.4
    container_name: mysql_primary
    environment:
      MARIADB_ROOT_PASSWORD: mysql
      MARIADB_DATABASE: mysql
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mariadb
    healthcheck:
      <<: *healthcheck-common
      test: 'mariadb-admin -pmysql ping'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis
      - app

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app
      - memcached

  yard:
    <<: *app-common
    container_name: yard
    pull_policy: never
    ports:
      - 8808:8808
    command: [ "bundle", "exec", "yard", "server", "--reload"]
    volumes:
      - .:/app
      - yard:/app/.yardoc

networks:
  app:
  postgres:
  mariadb:
  redis:
  memcached:

volumes:
  bundle:
  mariadb:
  postgres_primary:
  postgres_replica:
  yard:
