test:
  postgresql_primary: &postgresql_primary
    adapter: postgresql_proxy
    username: <%= ENV.fetch("PG_PRIMARY_USER", "postgres") %>
    password: <%= ENV.fetch("PG_PRIMARY_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("PG_PRIMARY_HOST", "localhost") %>
    port: <%= Integer(ENV.fetch("PG_PRIMARY_PORT", 5432)) %>
    database: postgresql_primary_replica_proxy_test

  postgresql_replica:
    adapter: postgresql
    username: <%= ENV.fetch("PG_REPLICA_USER", "postgres") %>
    password: <%= ENV.fetch("PG_REPLICA_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("PG_REPLICA_HOST", "postgres_replica") %>
    port: <%= Integer(ENV.fetch("PG_REPLICA_PORT", 5433)) %>
    database: postgresql_primary_replica_proxy_test
    replica: true

  postgresql_database_tasks:
    <<: *postgresql_primary
    database: postgresql_primary_replica_proxy_database_tasks_test

  mysql2_primary: &mysql_primary
    adapter: mysql2_proxy
    username: <%= ENV.fetch("MYSQL_PRIMARY_USER", "mysql") %>
    password: <%= ENV.fetch("MYSQL_PRIMARY_PASSWORD", "mysql") %>
    host: <%= ENV.fetch("MYSQL_PRIMARY_HOST", "localhost") %>
    port: <%= Integer(ENV.fetch("MYSQL_PRIMARY_PORT", 3306)) %>
    database: mysql_primary_replica_proxy_test

  mysql2_replica:
    adapter: mysql2
    username: <%= ENV.fetch("MYSQL_REPLICA_USER", "mysql") %>
    password: <%= ENV.fetch("MYSQL_REPLICA_PASSWORD", "mysql") %>
    host: <%= ENV.fetch("MYSQL_REPLICA_HOST", "mysql_replica") %>
    port: <%= Integer(ENV.fetch("MYSQL_REPLICA_PORT", 3307)) %>
    database: mysql_primary_replica_proxy_test
    replica: true

  mysql2_database_tasks:
    <<: *mysql_primary
    database: mysql_primary_replica_proxy_database_tasks_test
