test:
  postgresql_primary: &postgresql_primary
    adapter: postgresql_proxy
    username: <%= ENV.fetch("PG_PRIMARY_USER", "postgres") %>
    password: <%= ENV.fetch("PG_PRIMARY_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("PG_PRIMARY_HOST", "localhost") %>
    port: <%= Integer(ENV.fetch("PG_PRIMARY_PORT", 5432)) %>
    database: postgresql_primary_replica_proxy_test<%= ENV['TEST_ENV_NUMBER'] %>

  postgresql_replica:
    adapter: postgresql
    username: <%= ENV.fetch("PG_REPLICA_USER", "postgres") %>
    password: <%= ENV.fetch("PG_REPLICA_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("PG_REPLICA_HOST", "postgres_replica") %>
    port: <%= Integer(ENV.fetch("PG_REPLICA_PORT", 5433)) %>
    database: postgresql_primary_replica_proxy_test<%= ENV['TEST_ENV_NUMBER'] %>
    replica: true

  postgresql_database_tasks:
    <<: *postgresql_primary
    database: postgresql_primary_replica_proxy_database_tasks_test<%= ENV['TEST_ENV_NUMBER'] %>

  mysql2_primary: &mysql_primary
    adapter: mysql2_proxy
    username: <%= ENV.fetch("MYSQL_PRIMARY_USER", "mysql") %>
    password: <%= ENV.fetch("MYSQL_PRIMARY_PASSWORD", "mysql") %>
    host: <%= ENV.fetch("MYSQL_PRIMARY_HOST", "localhost") %>
    port: <%= Integer(ENV.fetch("MYSQL_PRIMARY_PORT", 3306)) %>
    database: mysql_primary_replica_proxy_test<%= ENV['TEST_ENV_NUMBER'] %>

  mysql2_replica:
    adapter: mysql2
    username: <%= ENV.fetch("MYSQL_REPLICA_USER", "mysql") %>
    password: <%= ENV.fetch("MYSQL_REPLICA_PASSWORD", "mysql") %>
    host: <%= ENV.fetch("MYSQL_REPLICA_HOST", "mysql_replica") %>
    port: <%= Integer(ENV.fetch("MYSQL_REPLICA_PORT", 3307)) %>
    database: mysql_primary_replica_proxy_test<%= ENV['TEST_ENV_NUMBER'] %>
    replica: true

  mysql2_database_tasks:
    <<: *mysql_primary
    database: mysql_primary_replica_proxy_database_tasks_test<%= ENV['TEST_ENV_NUMBER'] %>

  trilogy_primary: &trilogy_primary
    adapter: trilogy_proxy
    username: <%= ENV.fetch("MYSQL_PRIMARY_USER", "mysql") %>
    password: <%= ENV.fetch("MYSQL_PRIMARY_PASSWORD", "mysql") %>
    host: <%= ENV.fetch("MYSQL_PRIMARY_HOST", "localhost") %>
    port: <%= Integer(ENV.fetch("MYSQL_PRIMARY_PORT", 3306)) %>
    database: trilogy_primary_replica_proxy_test<%= ENV['TEST_ENV_NUMBER'] %>

  trilogy_replica:
    adapter: trilogy
    username: <%= ENV.fetch("MYSQL_REPLICA_USER", "mysql") %>
    password: <%= ENV.fetch("MYSQL_REPLICA_PASSWORD", "mysql") %>
    host: <%= ENV.fetch("MYSQL_REPLICA_HOST", "mysql_replica") %>
    port: <%= Integer(ENV.fetch("MYSQL_REPLICA_PORT", 3307)) %>
    database: trilogy_primary_replica_proxy_test<%= ENV['TEST_ENV_NUMBER'] %>
    replica: true

  trilogy_database_tasks:
    <<: *trilogy_primary
    database: trilogy_primary_replica_proxy_database_tasks_test<%= ENV['TEST_ENV_NUMBER'] %>

  sqlite3_primary: &sqlite3_primary
    adapter: sqlite3_proxy
    database: db/test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3

  sqlite3_replica:
    adapter: sqlite3
    database: db/test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
    replica: true

  sqlite3_database_tasks:
    <<: *sqlite3_primary
    database: db/database_tasks_test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
