name: Prebuild App Image

on:
  pull_request:
    paths:
      - '.app-image-tag'
  push:
    branches:
      - main
      - v0.1
      - v0.2
      - v0.3
      - v-0-4-stable
      - v-0-5-stable
      - v-0-6-stable
      - v-0-7-stable
      - v-0-8-stable
      - v-0-9-stable
    paths:
      - '.app-image-tag'
jobs:
  export_variables:
    runs-on: ubuntu-latest

    outputs:
      app_image: ${{ steps.compute_container_registry_name.outputs.CR_NAME }}/app:${{ steps.read_image_tag.outputs.APP_IMAGE_TAG }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compute container registry name
      id: compute_container_registry_name
      run: echo "CR_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Read image tag for app
      id: read_image_tag
      run: echo "APP_IMAGE_TAG=$(head -n1 .app-image-tag)" >> $GITHUB_OUTPUT

  prebuild_app:
    needs: export_variables
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - "3.2.9"
          - "3.3.9"
          - "3.4.7"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag app Docker image
      run: docker build --build-arg RUBY_VERSION=${{ matrix.ruby }} -f Dockerfile -t ${{ needs.export_variables.outputs.app_image }}-${{ matrix.ruby }} .

    - name: Push app Docker image
      run: docker push ${{ needs.export_variables.outputs.app_image }}-${{ matrix.ruby }}
