name: Build Postgres Primary Image

on:
  pull_request:
    paths:
      - 'docker/postgres_primary/Dockerfile'

jobs:
  export_variables:
    runs-on: ubuntu-latest

    outputs:
      primary_image: ${{ steps.compute_container_registry_name.outputs.CR_NAME }}/postgres_primary:${{ steps.calculate_primary_sha.outputs.PRIMARY_SHA }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compute container registry name
      id: compute_container_registry_name
      run: echo "CR_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Calculate SHA256 for docker/postgres_primary/Dockerfile
      id: calculate_primary_sha
      run: echo "PRIMARY_SHA=$(sha256sum docker/postgres_primary/Dockerfile | awk '{ print substr($1, 1, 12) }')" >> $GITHUB_OUTPUT

  prebuild_primary:
    needs: export_variables
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag primary Docker image
      run: docker build -t ${{ needs.export_variables.outputs.primary_image }} docker/postgres_primary

    - name: Push primary Docker image
      run: docker push ${{ needs.export_variables.outputs.primary_image }}
